### ISSUE TITLE
Problems creating dev environment on Orolo

### ISSUE THREAD

**Issue by ArtPoon** [western-bioinfo/western-bioinfo.github.io#11]
```console
art@orolo:~/git/western-bioinfo.github.io$ bundle exec jekyll build
/home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/sass-3.7.4/lib/sass/engine.rb:46:in `require': cannot load such file -- sass/environment (LoadError)
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/sass-3.7.4/lib/sass/engine.rb:46:in `<top (required)>'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/sass-3.7.4/lib/sass.rb:99:in `require'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/sass-3.7.4/lib/sass.rb:99:in `<top (required)>'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:3:in `require'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll-sass-converter.rb:4:in `require'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-sass-converter-1.5.2/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.3/lib/jekyll.rb:200:in `require'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.3/lib/jekyll.rb:200:in `<top (required)>'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.3/exe/jekyll:8:in `require'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/gems/jekyll-3.9.3/exe/jekyll:8:in `<top (required)>'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `load'
	from /home/art/git/western-bioinfo.github.io/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `<main>'
```

**Comment by ArtPoon** [comment]
```console
art@orolo:~/git/western-bioinfo.github.io$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
art@orolo:~/git/western-bioinfo.github.io$ gem -v
3.3.5
```

**Comment by ArtPoon** [comment]
Trying to use `rbenv` to install a different version of Ruby:
```console
art@orolo:~/git/western-bioinfo.github.io$ rbenv install 2.7.1
Downloading ruby-2.7.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.bz2
Installing ruby-2.7.1...

BUILD FAILED (Ubuntu 22.04 using ruby-build 20200401)

Inspect or clean up the working tree at /tmp/ruby-build.20230911152333.229298.gyZTBg
Results logged to /tmp/ruby-build.20230911152333.229298.log

Last 10 log lines:
linking shared-object date_core.so
make[2]: Leaving directory '/tmp/ruby-build.20230911152333.229298.gyZTBg/ruby-2.7.1/ext/date'
ripper.y: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
linking shared-object ripper.so
make[2]: Leaving directory '/tmp/ruby-build.20230911152333.229298.gyZTBg/ruby-2.7.1/ext/ripper'
make[1]: Leaving directory '/tmp/ruby-build.20230911152333.229298.gyZTBg/ruby-2.7.1'
make: *** [uncommon.mk:295: build-ext] Error 2
```
Related issue: https://github.com/rbenv/ruby-build/discussions/2172

**Comment by ArtPoon** [comment]
Installed newest release of `ruby-build` from GitHub repo, `rbenv` now lists a much larger selection of available installs

**Comment by ArtPoon** [comment]
Finally resolved.  
```console
art@orolo:~/git/western-bioinfo.github.io$ export PATH="$HOME/.rbenv/shims:$PATH"
art@orolo:~/git/western-bioinfo.github.io$ rbenv install 3.0.0
To follow progress, use 'tail -f /tmp/ruby-build.20230911155041.267095.log' or pass --verbose
Downloading openssl-1.1.1v.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/d6697e2871e77238460402e9362d47d18382b15ef9f246aba6c7bd780d38a6b0
Installing openssl-1.1.1v...
Installed openssl-1.1.1v to /home/art/.rbenv/versions/3.0.0

Downloading ruby-3.0.0.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.0.tar.gz
Installing ruby-3.0.0...
Installed ruby-3.0.0 to /home/art/.rbenv/versions/3.0.0

art@orolo:~/git/western-bioinfo.github.io$ rbenv local 3.0.0
art@orolo:~/git/western-bioinfo.github.io$ which ruby
/home/art/.rbenv/shims/ruby
art@orolo:~/git/western-bioinfo.github.io$ ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
art@orolo:~/git/western-bioinfo.github.io$ bundle install
Warning: the running version of Bundler (2.2.3) is older than the version that created the lockfile (2.3.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.4`.
art@orolo:~/git/western-bioinfo.github.io$ gem install bundler:2.3.4
Fetching bundler-2.3.4.gem
Successfully installed bundler-2.3.4
Parsing documentation for bundler-2.3.4
Installing ri documentation for bundler-2.3.4
Done installing documentation for bundler after 0 seconds
1 gem installed
art@orolo:~/git/western-bioinfo.github.io$ bundle install
Fetching gem metadata from https://rubygems.org/.........
art@orolo:~/git/western-bioinfo.github.io$ bundle exec jekyll build
Configuration file: /home/art/git/western-bioinfo.github.io/_config.yml
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
            Source: /home/art/git/western-bioinfo.github.io
       Destination: /home/art/git/western-bioinfo.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 4.589 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
art@orolo:~/git/western-bioinfo.github.io$ bundle exec jekyll serve
Configuration file: /home/art/git/western-bioinfo.github.io/_config.yml
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
            Source: /home/art/git/western-bioinfo.github.io
       Destination: /home/art/git/western-bioinfo.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 4.318 seconds.
 Auto-regeneration: enabled for '/home/art/git/western-bioinfo.github.io'
    Server address: http://127.0.0.1:4000
  Server running... press ctrl-c to stop.
```
